# -*- coding: utf-8 -*-
"""Internship_GIQ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rnlvaQRSITUeL3ZAKPL2WJQERrhQEYSX
"""

import numpy as np
import matplotlib.pyplot as plt

beta = 1e-8
lam = 1e9
E_S = 1.0
x_max = beta * lam

def p(x):
    return np.exp(-x) / (1 + np.exp(-x))

def entropy(x):
    p0 = p(x)
    eps = 1e-15
    p0 = np.clip(p0, eps, 1-eps)
    return -p0*np.log(p0) - (1-p0)*np.log(1-p0)

def relative_entropy(x1, x2):
    p1 = p(x1)
    p2 = p(x2)

    return p1*np.log(p1/p2) + (1-p1)*np.log((1-p1)/(1-p2))


def beta_delta_E(N):
    if N == 0:
        return 0.0

    x_vals = np.linspace(0, x_max, N+1)
    total = 0.0
    for j in range(N):
        total += relative_entropy(x_vals[j], x_vals[j+1])

    return total

N_values = np.arange(1, 101)
values_RW = [beta_delta_E(N) for N in N_values]

plt.figure()
plt.loglog(N_values, values_RW)
plt.xlabel('N', fontsize=12)
plt.ylabel(r'Dissipation', fontsize=12)

plt.xticks([10, 100], [r'$10^{1}$', r'$10^2$'])
plt.yticks([1e-2, 1e-1, 1e0, 1e1],
           [r'$10^{-2}$', r'$10^{-1}$', r'$10^{0}$', r'$10^{1}$'])

plt.grid(True, which='major', linestyle='-', alpha=0.7)

plt.xlim(1, 100)
plt.ylim(0.01, 5)
plt.tight_layout()
plt.show()

N = 100
x_max = 10   # because beta * epsilon_max = 10

# Linear RW gaps
j = np.arange(0, N+1)
x_vals_RW = j / N * x_max

plt.figure()
plt.plot(j, x_vals_RW)
plt.xlabel("j")
plt.ylabel(r"$\beta \epsilon_j$")
plt.title("RW protocol: linear machine gaps (N=100)")
plt.grid(True)
plt.show()

"""all of the slopes should be linear for large N

Try the red curve and then solve analyticially the linear case and compare
"""

import numpy as np
import matplotlib.pyplot as plt

x_max = 10.0

def p_from_x(x):
    return np.exp(-x)/(1+np.exp(-x))

def relative_entropy(x1, x2):
    p1 = p_from_x(x1)
    p2 = p_from_x(x2)

    return p1*np.log(p1/p2) + (1-p1)*np.log((1-p1)/(1-p2))

def beta_delta_E_SSP(N):
    if N == 0:
        return 0.0

    # linear populations
    p_hot = 0.5
    p_cold = p_from_x(x_max)

    p_vals = np.linspace(p_hot, p_cold, N+1)

    x_vals = np.log((1-p_vals)/p_vals)

    total = 0.0
    for j in range(N):
        total += relative_entropy(x_vals[j], x_vals[j+1])

    return total


N_values = np.arange(1,101)
values_SSP = np.array([beta_delta_E_SSP(N) for N in N_values])

plt.xlim(1, 100)
plt.ylim(0.01, 5)
plt.loglog(N_values, values_SSP)
plt.grid(True)
plt.show()

# SSP gaps from linear populations
N = 100

p_start = 0.5
p_end = np.exp(-10)/(1+np.exp(-10))   # final population corresponding to x_max=10

j = np.arange(0, N+1)

p_vals = np.linspace(p_start, p_end, N+1)

# Convert populations to gaps: x = ln((1-p)/p)
x_vals_SSP = np.log((1-p_vals)/p_vals)

# Plot gaps
plt.figure()
plt.plot(j, x_vals_SSP)
plt.xlabel("j")
plt.ylabel(r"$\beta \epsilon_j$")
plt.title("SSP protocol: gaps from linear populations (N=100)")
plt.grid(True)
plt.show()

plt.loglog(N_values, values_SSP, label='SSP', color='red')
plt.loglog(N_values, values_RW, label='RW', color='green')

plt.xlabel('N', fontsize=12)
plt.ylabel(r'Dissipation', fontsize=12)

plt.xlim(1, 100)
plt.ylim(0.01, 5)
plt.grid(True)
plt.legend()
plt.show()

plt.figure()
plt.plot(j, x_vals_SSP, color='red')
plt.plot(j, x_vals_RW, color='green')
plt.xlabel("j")
plt.ylabel(r"$\beta \epsilon_j$")
plt.title("Gaps")
plt.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

x_max = 10.0

import numpy as np
import matplotlib.pyplot as plt

def p(x):
    return np.exp(-x)/(1+np.exp(-x))

def integrand(tau):
    x = x_max * tau
    p_tau = p(x)

    dot_x = x_max  # derivative of x with respect to tau (RW linear case)

    return (dot_x**2) * p_tau - (p_tau * dot_x)**2

def W_diss(N):
    taus = np.linspace(0,1,5000)
    integral = np.trapz(integrand(taus), taus)
    return (1/(2*N)) * integral

N_values = np.arange(1,101)
values_user = np.array([W_diss(N) for N in N_values])

plt.figure()
plt.loglog(N_values, values_user, label="Using thermodynamical length")
plt.loglog(N_values, values_RW, label="Using relative entropy", color='green')
plt.xlabel("N")
plt.ylabel("Dissipation")
plt.grid(True, which='major')
plt.title("Different calculations for the RW protocol")
plt.legend()
plt.show()

beta = 1e-8
lam = 1e9
E_S = 1.0

def Z(beta):
    return 1 + np.exp(-beta * E_S)

Z_initial = Z(beta)
Z_final = Z(lam * beta)
Z_mid = Z(beta * (1 + lam) / 2)

arg = Z_mid / np.sqrt(Z_initial * Z_final)

L_star = 2 * np.arccos(arg)

def dissipation_TL(N):
    return (L_star**2) / (2 * N)

N_values_TL = np.arange(1, 101)
TL_values = np.array([dissipation_TL(N) for N in N_values])

plt.figure(figsize=(10, 6))
plt.loglog(N_values_TL, TL_values, color='blue', label=f'TL')
plt.loglog(N_values_TL, values_RW, color='green', label=f'RW')
plt.loglog(N_values_TL, values_SSP, color='red', label=f'SSP')

plt.xlabel("$N$", fontsize=12)
plt.ylabel(r"Dissipation", fontsize=12)
plt.title("Comparison of three Cooling Protocols", fontsize=14)

plt.grid(True, which='major', linestyle='-', alpha=0.7)

plt.xlim(1, 100)
plt.ylim(0.01, 5)
plt.legend(fontsize=11)
plt.tight_layout()
plt.show()